FROM node:carbon

RUN echo deb http://ftp.uk.debian.org/debian jessie-backports main \
    >>/etc/apt/sources.list

RUN apt-get update
RUN apt-get install ffmpeg -y

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install --only=production

# Bundle app source
COPY . .

EXPOSE 80

CMD [ "npm", "start" ]
